// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXUU3X2ogdEH6cnOY0abi4SCDe6320oTc',
    appId: '1:82314281320:android:0def5727ef79e6702516dd',
    messagingSenderId: '82314281320',
    projectId: 'likeehit-flutter-435116',
    databaseURL: 'https://likeehit-flutter-435116-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'likeehit-flutter-435116.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo_hKJ3TCr4DCkwfSgzu6m6UQoiuxbf20',
    appId: '1:82314281320:web:c88ad41a7a4e1c142516dd',
    messagingSenderId: '82314281320',
    projectId: 'likeehit-flutter-435116',
    authDomain: 'likeehit-flutter-435116.firebaseapp.com',
    databaseURL: 'https://likeehit-flutter-435116-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'likeehit-flutter-435116.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQNlLnM_gPya29Gp2LXP7MkaKfiSq5Zh4',
    appId: '1:82314281320:ios:87beb528f4f18a042516dd',
    messagingSenderId: '82314281320',
    projectId: 'likeehit-flutter-435116',
    databaseURL: 'https://likeehit-flutter-435116-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'likeehit-flutter-435116.firebasestorage.app',
    androidClientId: '82314281320-jf5r1juhlo852v9ionulvh12vhrfc9o1.apps.googleusercontent.com',
    iosClientId: '82314281320-ticgtoc5rbth1ipmuiv7gptdajlodjdg.apps.googleusercontent.com',
    iosBundleId: 'com.likeehit.app',
  );

}